[project]
name = "ai-scribe-reformatter"
version = "0.1.5"
description = "A tool to reformat the ai consultation notes produced by heidi the AI scribe tool. This tool is not affiliated with the Heidi organisation, all trademarks and copyrights belong to them."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "freesimplegui>=5.2.0.post1",
    "mouse>=0.7.1",
    "pillow>=12.1.0",
    "pyautogui>=0.9.54",
    "pyinstaller>=6.17.0",
    "pyperclip>=1.11.0",
    "pystray>=0.19.5",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
